/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package event.management.system;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cash
 */
public class eventPlanning_interface extends javax.swing.JFrame {

    /**
     * Creates new form eventPlanning_interface
     */
    public eventPlanning_interface() {
        initComponents();
        initializeTableModel();
    }
    
    private void initializeTableModel() {
        // Define column names for the table model
        String[] columnNames = {"Event Name", "Date", "Time", "Description", "Organiser"};
        
        // Initialize tableModel with column names and 0 rows initially
        tableModel = new DefaultTableModel(columnNames, 0);
        
        // Set the table model to your JTable instance
        eventPlanning_table.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eventName_txtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        eventDate_txtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        eventTime_txtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        eventDescription_txtField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventPlanning_table = new javax.swing.JTable();
        event_addBtn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        viewEvent_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        eventOrganiser_txtField = new javax.swing.JTextField();
        delete_btn = new javax.swing.JButton();
        event_editBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Rockwell Nova Extra Bold", 1, 14)); // NOI18N
        jLabel1.setText("Event Planning");

        jLabel2.setFont(new java.awt.Font("Rockwell Nova Extra Bold", 1, 14)); // NOI18N
        jLabel2.setText("Event Name");

        eventName_txtField.setToolTipText("add event name...");
        eventName_txtField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Rockwell Nova Extra Bold", 1, 14)); // NOI18N
        jLabel3.setText("Date");

        eventDate_txtField.setToolTipText("add event date...");
        eventDate_txtField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Rockwell Nova Extra Bold", 1, 14)); // NOI18N
        jLabel4.setText("Time");

        eventTime_txtField.setToolTipText("add event time...");
        eventTime_txtField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Rockwell Nova Extra Bold", 1, 14)); // NOI18N
        jLabel5.setText("Description");

        eventDescription_txtField.setToolTipText("add event description...");
        eventDescription_txtField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        eventPlanning_table.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eventPlanning_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(eventPlanning_table);

        event_addBtn.setText("Add");
        event_addBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        event_addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                event_addBtnActionPerformed(evt);
            }
        });

        back_btn.setText("Back");
        back_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        viewEvent_btn.setText("View");
        viewEvent_btn.setToolTipText("");
        viewEvent_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewEvent_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEvent_btnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Rockwell Nova Extra Bold", 1, 14)); // NOI18N
        jLabel6.setText("Organiser");

        eventOrganiser_txtField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        delete_btn.setText("Delete");
        delete_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        event_editBtn.setText("Edit");
        event_editBtn.setToolTipText("To edit an event, write the name of the event");
        event_editBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        event_editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                event_editBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(viewEvent_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(jLabel2)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eventName_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(eventDescription_txtField, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                                            .addComponent(eventDate_txtField)
                                            .addComponent(eventTime_txtField, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(eventOrganiser_txtField))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(delete_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(event_addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(event_editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(eventName_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(eventDate_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eventTime_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(event_addBtn)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventDescription_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(event_editBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(eventOrganiser_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_btn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewEvent_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        
        dispose();
        
        start_interface start = new start_interface();
        start.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private void event_addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_event_addBtnActionPerformed
        // TODO add your handling code here:
        
         //textfield getters
        //whatever information that will be typed in the textfield will be stored in a variable
        String e_Name = eventName_txtField.getText();
        String e_Date = eventDate_txtField.getText();
        String e_Time = eventTime_txtField.getText();
        String e_description = eventDescription_txtField.getText();
        String e_organiser = eventOrganiser_txtField.getText();

        Connection connection = Database_Connection.getConnection();
        try {
            // Insert into passenger_details table
            String insertQuery = "INSERT INTO event_planning (e_name, e_date, e_time, e_description, e_organiser) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement insertStatement = connection.prepareStatement(insertQuery);
            insertStatement.setString(1, e_Name);
            insertStatement.setString(2, e_Date);
            insertStatement.setString(3, e_Time);
            insertStatement.setString(4, e_description);
            insertStatement.setString(5, e_organiser);
            insertStatement.executeUpdate();
            
            //the next four lines of code will clear the textfields after inserting the information
            eventName_txtField.setText("");
            eventDate_txtField.setText("");
            eventTime_txtField.setText("");
            eventDescription_txtField.setText("");
            eventOrganiser_txtField.setText("");

            JOptionPane.showMessageDialog(this, "Event added successfully!");
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_event_addBtnActionPerformed

    private void viewEvent_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEvent_btnActionPerformed
        // TODO add your handling code here:
        
        Connection connection = Database_Connection.getConnection();
        // Clear the table model
        tableModel.setRowCount(0);
        try {
            Statement stmt = connection.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM event_planning");

            // show the table with data from the result set
            while (rs.next()) {
                String e_name = rs.getString("e_name");
                String e_date = rs.getString("e_date");
                String e_time = rs.getString("e_time");
                String e_description = rs.getString("e_description");
                String e_organiser = rs.getString("e_organiser");
                tableModel.addRow(new Object[]{e_name, e_date, e_time, e_description, e_organiser});
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_viewEvent_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        String e_Name = eventName_txtField.getText();
        String sql = "DELETE FROM event_planning WHERE e_name = ?";

        try (Connection conn = Database_Connection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setString(1, e_Name);
            int rowsAffected = stmt.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null,"Event deleted successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "No event found with the given name.");
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void event_editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_event_editBtnActionPerformed
        // TODO add your handling code here:
        String e_Name = eventName_txtField.getText();
        String e_Date = eventDate_txtField.getText();
        String e_Time = eventTime_txtField.getText();
        String e_description = eventDescription_txtField.getText();
        String e_organiser = eventOrganiser_txtField.getText();
        String currentName = JOptionPane.showInputDialog(null, "Enter the name of the event you want to update");
        
        String sql = "UPDATE event_planning SET e_name = ?, e_date = ?, e_time = ?, e_description = ?, e_organiser = ? WHERE e_name = ?";

        try (Connection conn = Database_Connection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setString(1, e_Name);
            stmt.setString(2, e_Date);
            stmt.setString(3, e_Time);
            stmt.setString(4, e_description);
            stmt.setString(5, e_organiser);
            stmt.setString(6, currentName);

            int rowsAffected = stmt.executeUpdate();

            if (rowsAffected > 0) {
                System.out.println("Event updated successfully!");
            } else {
                System.out.println("No event found with the given name.");
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_event_editBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eventPlanning_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eventPlanning_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eventPlanning_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eventPlanning_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eventPlanning_interface().setVisible(true);
            }
        });
    }

    private DefaultTableModel tableModel;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton delete_btn;
    private javax.swing.JTextField eventDate_txtField;
    private javax.swing.JTextField eventDescription_txtField;
    private javax.swing.JTextField eventName_txtField;
    private javax.swing.JTextField eventOrganiser_txtField;
    private javax.swing.JTable eventPlanning_table;
    private javax.swing.JTextField eventTime_txtField;
    private javax.swing.JButton event_addBtn;
    private javax.swing.JButton event_editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewEvent_btn;
    // End of variables declaration//GEN-END:variables
}
