/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package event.management.system;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cash
 */
public class venue_interface extends javax.swing.JFrame {

    /**
     * Creates new form venue_interface
     */
    public venue_interface() {
        initComponents();
        initializeTableModel();
    }
    
    private void initializeTableModel() {
        // Define column names for the table model
        String[] columnNames = {"Venue Name", "Address", "Capacity", "Availability"};
        
        // Initialize tableModel with column names and 0 rows initially
        tableModel = new DefaultTableModel(columnNames, 0);
        
        // Set the table model to your JTable instance
        venueManagement_table.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        venueName_txtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        venueAddress_txtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        venueCapacity_txtfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        venueAvailability_txtField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        venueManagement_table = new javax.swing.JTable();
        back_btn = new javax.swing.JButton();
        venue_addbtn = new javax.swing.JButton();
        venue_viewbtn = new javax.swing.JButton();
        venue_editbtn = new javax.swing.JButton();
        venue_deletebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel1.setText("Venue Management");

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel2.setText("Venue Name");

        venueName_txtField.setToolTipText("add venue name...");
        venueName_txtField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel3.setText("Address");

        venueAddress_txtField.setToolTipText("add venue address...");
        venueAddress_txtField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel4.setText("Capacity");

        venueCapacity_txtfield.setToolTipText("add venue capacity...");
        venueCapacity_txtfield.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel5.setText("Availabiilty");

        venueAvailability_txtField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        venueManagement_table.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        venueManagement_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(venueManagement_table);

        back_btn.setText("Back");
        back_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        venue_addbtn.setText("Add");
        venue_addbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        venue_addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venue_addbtnActionPerformed(evt);
            }
        });

        venue_viewbtn.setText("View");
        venue_viewbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        venue_viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venue_viewbtnActionPerformed(evt);
            }
        });

        venue_editbtn.setText("Edit");
        venue_editbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        venue_editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venue_editbtnActionPerformed(evt);
            }
        });

        venue_deletebtn.setText("Delete");
        venue_deletebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        venue_deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venue_deletebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(venue_viewbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(venueCapacity_txtfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                                    .addComponent(venueAddress_txtField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(venueAvailability_txtField)
                                    .addComponent(venueName_txtField, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(venue_editbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(venue_deletebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(venue_addbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(venueName_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(venueAddress_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(venue_addbtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(venueCapacity_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(venue_editbtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(venueAvailability_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(venue_deletebtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue_viewbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        dispose();
        
        start_interface start = new start_interface();
        start.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private void venue_addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venue_addbtnActionPerformed
        // TODO add your handling code here:
        
         //textfield getters
        //whatever information that will be typed in the textfield will be stored in a variable
        String v_name = venueName_txtField.getText();
        String v_address = venueAddress_txtField.getText();
        String v_capacity = venueCapacity_txtfield.getText();
        String v_availabilty = venueAvailability_txtField.getText();

        Connection connection = Database_Connection.getConnection();
        try {
            // Insert into passenger_details table
            String insertQuery = "INSERT INTO venue_management (v_name, v_address, v_capacity, v_availabilty) VALUES (?, ?, ?, ?)";
            PreparedStatement insertStatement = connection.prepareStatement(insertQuery);
            insertStatement.setString(1, v_name);
            insertStatement.setString(2, v_address);
            insertStatement.setString(3, v_capacity);
            insertStatement.setString(4, v_availabilty);
            insertStatement.executeUpdate();
            
            //the next four lines of code will clear the textfields after inserting the information
            venueName_txtField.setText("");
            venueAddress_txtField.setText("");
            venueCapacity_txtfield.setText("");
            venueAvailability_txtField.setText("");

            JOptionPane.showMessageDialog(this, "Venue added successfully!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_venue_addbtnActionPerformed

    private void venue_viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venue_viewbtnActionPerformed
        // TODO add your handling code here:
        Connection connection = Database_Connection.getConnection();
        // Clear the table model
        tableModel.setRowCount(0);
        try {
            Statement stmt = connection.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM venue_management");

            // show the table with data from the result set
            while (rs.next()) {
                String v_name = rs.getString("v_name");
                String v_address = rs.getString("v_address");
                String v_capacity = rs.getString("v_capacity");
                String v_availabilty = rs.getString("v_availabilty");
                tableModel.addRow(new Object[]{v_name, v_address, v_capacity, v_availabilty});
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_venue_viewbtnActionPerformed

    private void venue_editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venue_editbtnActionPerformed
        // TODO add your handling code here:
        String v_name = venueName_txtField.getText();
        String v_address = venueAddress_txtField.getText();
        String v_capacity = venueCapacity_txtfield.getText();
        String v_availabilty = venueAvailability_txtField.getText();
        String currentName = JOptionPane.showInputDialog(null, "Enter the name of the venue you want to update");
        
        String sql = "UPDATE venue_management SET v_name = ?, v_address = ?, v_capacity = ?, v_availabilty = ? WHERE v_name = ?";

        try (Connection connection = Database_Connection.getConnection();
             PreparedStatement insertStatement = connection.prepareStatement(sql)) {

            insertStatement.setString(1, v_name);
            insertStatement.setString(2, v_address);
            insertStatement.setString(3, v_capacity);
            insertStatement.setString(4, v_availabilty);
            insertStatement.setString(5, currentName);

            int rowsAffected = insertStatement.executeUpdate();

            if (rowsAffected > 0) {
                System.out.println("Venue details updated successfully!");
            } else {
                System.out.println("No Venue found with the given name.");
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_venue_editbtnActionPerformed

    private void venue_deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venue_deletebtnActionPerformed
        // TODO add your handling code here:
        String v_name = venueName_txtField.getText();
        String sql = "DELETE FROM venue_management WHERE v_name = ?";

        try (Connection conn = Database_Connection.getConnection();
             PreparedStatement insertStatement = conn.prepareStatement(sql)) {

            insertStatement.setString(1, v_name);
            int rowsAffected = insertStatement.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null,"Venue deleted successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "No venue found with the given name.");
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_venue_deletebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(venue_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(venue_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(venue_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(venue_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new venue_interface().setVisible(true);
            }
        });
    }

    private DefaultTableModel tableModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField venueAddress_txtField;
    private javax.swing.JTextField venueAvailability_txtField;
    private javax.swing.JTextField venueCapacity_txtfield;
    private javax.swing.JTable venueManagement_table;
    private javax.swing.JTextField venueName_txtField;
    private javax.swing.JButton venue_addbtn;
    private javax.swing.JButton venue_deletebtn;
    private javax.swing.JButton venue_editbtn;
    private javax.swing.JButton venue_viewbtn;
    // End of variables declaration//GEN-END:variables
}
